/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PayloadRouteImport } from './routes/_payload'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as PayloadAdminIndexRouteImport } from './routes/_payload.admin.index'
import { Route as PayloadAdminSplatRouteImport } from './routes/_payload.admin.$'
import { Route as PayloadApiSplatRouteImport } from './routes/_payload.api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadApiSplatRoute = PayloadApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => PayloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/admin': typeof PayloadAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_payload': typeof PayloadRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/api/$': typeof PayloadApiSplatRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/docs/$slug' | '/admin/$' | '/api/$' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/docs/$slug' | '/admin/$' | '/api/$' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_payload'
    | '/docs/$slug'
    | '/_payload/admin/$'
    | '/_payload/api/$'
    | '/_payload/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PayloadRoute: typeof PayloadRouteWithChildren
  DocsSlugRoute: typeof DocsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/api/$': {
      id: '/_payload/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof PayloadApiSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
  }
}

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadApiSplatRoute: typeof PayloadApiSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadApiSplatRoute: PayloadApiSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PayloadRoute: PayloadRouteWithChildren,
  DocsSlugRoute: DocsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
